name: Validar nome da branch

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  checar-nome-da-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validando nome da branch
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch atual: $BRANCH_NAME"
          
          REGEX='^(backend|frontend|docs|database)/[a-z0-9\-]+$'

          if [[ "$BRANCH_NAME" =~ $REGEX ]]; then
            echo "✅ Nome de branch válido"
          else
            echo "❌ Nome de branch inválido: $BRANCH_NAME"
            echo "Use o formato: area/nome-da-tarefa"
            echo "Exemplo válido: frontend/ajustar-layout"
            echo "Áreas permitidas: backend, frontend, docs, database"
            exit 1
          fi
